/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FolderId = IDL.Nat;
export const Folder = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'modifiedDate' : IDL.Int,
  'parentId' : IDL.Opt(FolderId),
});
export const TagId = IDL.Nat;
export const Tag = IDL.Record({
  'id' : TagId,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const FileId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadata = IDL.Record({
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat64,
  'description' : IDL.Text,
  'fileType' : IDL.Text,
  'modifiedDate' : IDL.Int,
  'tagIds' : IDL.Vec(TagId),
  'folderId' : IDL.Opt(FolderId),
  'uploadDate' : IDL.Int,
});
export const FolderContents = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'folders' : IDL.Vec(Folder),
});
export const Profile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
  'createTag' : IDL.Func([IDL.Text, IDL.Text], [Tag], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'deleteFolder' : IDL.Func([FolderId], [], []),
  'deleteTag' : IDL.Func([TagId], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getAllFilesInFolder' : IDL.Func(
      [IDL.Opt(FolderId)],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'getFolderContents' : IDL.Func(
      [IDL.Opt(FolderId)],
      [FolderContents],
      ['query'],
    ),
  'getFolderPath' : IDL.Func([FolderId], [IDL.Vec(Folder)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getTag' : IDL.Func([TagId], [Tag], ['query']),
  'moveFile' : IDL.Func([FileId, IDL.Opt(FolderId)], [FileMetadata], []),
  'moveFolder' : IDL.Func([FolderId, IDL.Opt(FolderId)], [Folder], []),
  'renameFolder' : IDL.Func([FolderId, IDL.Text], [Folder], []),
  'searchFilesWithTags' : IDL.Func(
      [IDL.Text, IDL.Vec(TagId)],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'updateFile' : IDL.Func(
      [FileId, IDL.Text, IDL.Text, IDL.Vec(TagId)],
      [FileMetadata],
      [],
    ),
  'updateTag' : IDL.Func([TagId, IDL.Text, IDL.Text], [Tag], []),
  'uploadFile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(TagId),
        IDL.Opt(FolderId),
        IDL.Nat64,
        IDL.Text,
        ExternalBlob,
      ],
      [FileMetadata],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FolderId = IDL.Nat;
  const Folder = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'modifiedDate' : IDL.Int,
    'parentId' : IDL.Opt(FolderId),
  });
  const TagId = IDL.Nat;
  const Tag = IDL.Record({
    'id' : TagId,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const FileId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadata = IDL.Record({
    'id' : FileId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat64,
    'description' : IDL.Text,
    'fileType' : IDL.Text,
    'modifiedDate' : IDL.Int,
    'tagIds' : IDL.Vec(TagId),
    'folderId' : IDL.Opt(FolderId),
    'uploadDate' : IDL.Int,
  });
  const FolderContents = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'folders' : IDL.Vec(Folder),
  });
  const Profile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
    'createTag' : IDL.Func([IDL.Text, IDL.Text], [Tag], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'deleteFolder' : IDL.Func([FolderId], [], []),
    'deleteTag' : IDL.Func([TagId], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getAllFilesInFolder' : IDL.Func(
        [IDL.Opt(FolderId)],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'getFolderContents' : IDL.Func(
        [IDL.Opt(FolderId)],
        [FolderContents],
        ['query'],
      ),
    'getFolderPath' : IDL.Func([FolderId], [IDL.Vec(Folder)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getTag' : IDL.Func([TagId], [Tag], ['query']),
    'moveFile' : IDL.Func([FileId, IDL.Opt(FolderId)], [FileMetadata], []),
    'moveFolder' : IDL.Func([FolderId, IDL.Opt(FolderId)], [Folder], []),
    'renameFolder' : IDL.Func([FolderId, IDL.Text], [Folder], []),
    'searchFilesWithTags' : IDL.Func(
        [IDL.Text, IDL.Vec(TagId)],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'updateFile' : IDL.Func(
        [FileId, IDL.Text, IDL.Text, IDL.Vec(TagId)],
        [FileMetadata],
        [],
      ),
    'updateTag' : IDL.Func([TagId, IDL.Text, IDL.Text], [Tag], []),
    'uploadFile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(TagId),
          IDL.Opt(FolderId),
          IDL.Nat64,
          IDL.Text,
          ExternalBlob,
        ],
        [FileMetadata],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };