/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FileId = bigint;
export interface FileMetadata {
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'description' : string,
  'fileType' : string,
  'modifiedDate' : bigint,
  'tagIds' : Array<TagId>,
  'folderId' : [] | [FolderId],
  'uploadDate' : bigint,
}
export interface Folder {
  'id' : FolderId,
  'name' : string,
  'createdDate' : bigint,
  'modifiedDate' : bigint,
  'parentId' : [] | [FolderId],
}
export interface FolderContents {
  'files' : Array<FileMetadata>,
  'folders' : Array<Folder>,
}
export type FolderId = bigint;
export interface Profile { 'name' : string }
export interface Tag { 'id' : TagId, 'name' : string, 'color' : string }
export type TagId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createFolder' : ActorMethod<[string, [] | [FolderId]], Folder>,
  'createTag' : ActorMethod<[string, string], Tag>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'deleteFolder' : ActorMethod<[FolderId], undefined>,
  'deleteTag' : ActorMethod<[TagId], undefined>,
  'getAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getAllFilesInFolder' : ActorMethod<[[] | [FolderId]], Array<FileMetadata>>,
  'getAllFolders' : ActorMethod<[], Array<Folder>>,
  'getAllTags' : ActorMethod<[], Array<Tag>>,
  'getFolderContents' : ActorMethod<[[] | [FolderId]], FolderContents>,
  'getFolderPath' : ActorMethod<[FolderId], Array<Folder>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getTag' : ActorMethod<[TagId], Tag>,
  'moveFile' : ActorMethod<[FileId, [] | [FolderId]], FileMetadata>,
  'moveFolder' : ActorMethod<[FolderId, [] | [FolderId]], Folder>,
  'renameFolder' : ActorMethod<[FolderId, string], Folder>,
  'searchFilesWithTags' : ActorMethod<
    [string, Array<TagId>],
    Array<FileMetadata>
  >,
  'setProfile' : ActorMethod<[string], undefined>,
  'updateFile' : ActorMethod<
    [FileId, string, string, Array<TagId>],
    FileMetadata
  >,
  'updateTag' : ActorMethod<[TagId, string, string], Tag>,
  'uploadFile' : ActorMethod<
    [
      string,
      string,
      Array<TagId>,
      [] | [FolderId],
      bigint,
      string,
      ExternalBlob,
    ],
    FileMetadata
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];